#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibs = [1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
#fibs = [0,1]
maxf = fibs.last
sum = 0
while maxf < 4000000 do
  a = fibs.last
  b = fibs[-2]
  n = a + b
  fibs<<n
  maxf=fibs.last
  puts maxf
end
fibs.each do |x|
  if x % 2 == 0
    sum = sum + x
  end
end
puts sum
  